name: workflow

on:
  push:
    branches:
      - main
    Paths-ignore:
        - 'README.md'

jobs:
  integration-test:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.12' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask fastapi numpy 
          pip install -r requirements.txt

      - name: Authenticate with Dagshub
        run: |
          export DAGSHUB_USERNAME="your_dagshub_username"
          export DAGSHUB_TOKEN="${{ secrets.DAGSHUB_TOKEN }}"
          echo "DAGSHUB_TOKEN set"

      - name: Lint code
        run: echo "Linting Repository"

      - name: Run Unit tests
        run: python -m unittest discover -s . -p "test_app.py"